# Generated by Django 4.1 on 2023-01-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="product",
            field=models.IntegerField(
                choices=[(1, "PÃO FRANÇÊS"), (2, "BOLO DO CACO"), (3, "PÃO ITALIANO")],
                max_length=20,
            ),
        ),
    ]
