# Generated by Django 4.1 on 2023-01-09 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            (1, "PÃO FRANÇÊS"),
                            (2, "BOLO DO CACO"),
                            (3, "PÃO ITALIANO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("complemento", models.CharField(max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
