# Generated by Django 4.1 on 2023-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
