# Generated by Django 4.1 on 2023-01-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baker", "0002_orders_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
