# Generated by Django 4.1 on 2023-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_of_order",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
