# Generated by Django 4.1 on 2023-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_order_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.DateTimeField(null=True),
        ),
    ]
